---
project_name: path-helper
dist: ./_output/dist

builds:
  - id: linux
    binary: path-helper
    main: cmd/path-helper/main.go
    goos:
      - linux
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -a
      - -mod=vendor
    goarch:
      - amd64
  - id: darwin
    binary: path-helper
    main: cmd/path-helper/main.go
    goos:
      - darwin
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -a
      - -mod=vendor
    goarch:
      - amd64