---
project_name: path-helper
dist: ./bin/dist

builds:
  - id: path-helper
    binary: path-helper
    main: cmd/path-helper/main.go
    goos:
      - linux
      - darwin
    env:
      - CGO_LDFLAGS="-s -w"
    flags:
      - -a
      - -v
    goarch:
      - amd64
      - arm64
