---
project_name: path-helper
dist: ./bin/dist

builds:
  - id: linux
    binary: path-helper
    main: cmd/path-helper/main.go
    goos:
      - linux
    env:
      - CGO_LDFLAGS="-s -w"
    flags:
      - -a
      - -v
    goarch:
      - amd64

  - id: darwin
    binary: path-helper
    main: cmd/path-helper/main.go
    goos:
      - darwin
    env:
      - CGO_LDFLAGS="-s -w"
    flags:
      - -a
      - -v
    goarch:
      - amd64
