---
project_name: path-helper
dist: ./build/dist

archive:
  format: tar.gz

builds:
  - id: linux
    binary: path-helper
    main: cmd/path-helper/main.go
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    flags:
      -a
    goarch:
      - amd64
  - id: darwin
    binary: path-helper
    main: cmd/path-helper/main.go
    goos:
      - darwin
    env:
      - CGO_ENABLED=0
    flags:
      -a
    goarch:
      - amd64