---
name: test

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup

      - shell: bash
        run: make build

      - shell: bash
        run: make test-unit

      - shell: bash
        run: make test-e2e
